\o /tmp/5_sequences.log

CREATE SEQUENCE seq_tipo_parametro 
INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE SEQUENCE seq_pessoa 
INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE SEQUENCE seq_perfil_acesso 
INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE SEQUENCE seq_caract 
INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE SEQUENCE seq_item 
INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE SEQUENCE seq_conteudo 
INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE SEQUENCE seq_conteudo_item 
INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;
 
CREATE SEQUENCE seq_conteudo_pessoa 
INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

